# Generated by Django 4.0.4 on 2022-08-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='adress',
            new_name='address',
        ),
    ]
